### ISSUE TITLE
Suggestion: Export recorded tours

### ISSUE THREAD

**Issue by bobmorane06** [pieterclaerhout/export-komoot#3]
Congrats on a very nice app, it worked flawlessly. However I wanted to export my completed rides to view a personal heatmap with the objective of trying new trails in my area (via https://erik.github.io/derive/). 

I don't know go but I tweaked your code and replaced "tour_planned" by "tour_recorded" and was successful downloading my completed tours. May I suggest that you add a command-line option to choose between planned and recorded? 

To be able to select which files to upload for the heatmap, I changed the filename to "tour.Date tour.Sport.ext" but it resulted in all my files being deleted so I commented the line "deleteWithPattern(args.To, id[0]+"*."+format)" in main.go. That's very dirty :-), would it make sense to also have a command line option to choose the format of filenames?

**Comment by pieterclaerhout** [comment]
I'll add the tour type as a command line option. 

For the filename pattern, that'll be a bigger challenge. Currently, I use the filename to verify if a tour still exists on Komoot or not (to be able to do a full sync). To be able to support custom filenames, I'll need to figure out a different way to do this...

Just to be clear, if you have the option to download all recorded tours, you can do a full download of them to a different folder. Doing so would not delete any files.

The only part that you would still be missing is the actual filename, right?

**Comment by bobmorane06** [comment]
Thank you Pieter. Don't break your head on the Filenames. 

I did not think of trying that myself, how about keeping the name you're currently using, but having the option to append within the filename a combination of the "type Tour struct" elements? For example "tour.ID, tour.ChangedAt.Unix(), tour.Date, tour.Sport, ext"

**Comment by pieterclaerhout** [comment]
@bobmorane06 I've made your filename suggestion the default now :)

**Comment by bobmorane06** [comment]
Tested, works great, thanks very much!
