### ISSUE TITLE
Can't seem to make it work

### ISSUE THREAD

**Issue by slambrechts** [pieterclaerhout/export-komoot#4]
Dear Pieter,

When I run

`~/exportkomoot/export-komoot$ make run-full`

I get:

```
make: execvp: go: Permission denied
make: *** [Makefile:12: init] Error 127
```

I cloned the repo and created the `.env` file inside containing my KOMOOT_EMAIL and KOMOOT_PASSWD before running the make cmd

Any idea what is wrong?

**Comment by pieterclaerhout** [comment]
Do you have Go installed?

https://go.dev/

**Comment by slambrechts** [comment]
ok thanks, that was idd the problem. Had to set GOBIN and GOPATH also (to a path where I have write permissions). Thank you and thank you for the tool!
